[project]
name = "file-splitter"
version = "0.1.0"
description = "Otimizador de arquivo para ser usado em transcrição local ou via API (whisper | openAI)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "moviepy==1.0.3",
    "pydub>=0.25.1",
    "streamlit>=1.46.1",
]
